include: package:lint/strict.yaml

linter:
  rules:
    avoid_print: true 
    prefer_double_quotes: true 
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    combinators_ordering: true
    comment_references: true
    dangling_library_doc_comments: true
    implicit_call_tearoffs: true
    invalid_case_patterns: true
    avoid_escaping_inner_quotes: false